Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 120
  Exclude: []

Metrics/AbcSize:
  Max: 19

Metrics/MethodLength:
  Max: 11